getground:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: <username>
      pass: <password>
      dbname: getground_test
      schema: source

    prod:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: <username>
      pass: <password>
      dbname: getground_test
      schema: source

  target: dev
